# Jekyll
exclude: ['nbproject', 'README.md', 'manifest.yml', 'rakefile.rb', 'Gemfile', 'Gemfile.lock', 'update.sh', 'localupdate.sh']
permalink:   /:title

future: false
markdown: rdiscount

# Site
iamantony:
    title: iamantony
