# Jekyll settings

# Exclude files/dirs from conversion during site building
exclude: ['README.md', "Gemfile", "Gemfile.lock", "node_modules"]

timezone: Europe/Moscow

# Publish posts or collection documents with a future date
future: false

# Show draft posts on site
show_drafts: false

# Cause a build to fail if there is a YAML syntax error in a page's front matter
strict_front_matter: true

# Site
iamantony:
    title: iamantony

# Set default values for files (http://jekyllrb.com/docs/configuration/#front-matter-defaults)
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
      author: "iamantony"
